development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sampleapp_development
  pool: 5
  timeout: 5000
  username: simkim22
  password: igualeja

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sampleapp_test
  pool: 5
  timeout: 5000
  username: simkim22
  password: igualeja
    
